management:

  endpoint:

    health:
      show-details: always

  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: sm

logging:
  level:
    com.spring.monitoring.controller: debug
